packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # all apps in subdirs of apps/
  - 'apps/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
