version: '3'

tasks:
  dev:
    desc: "Run Vite + Fastify in watch mode"
    cmds:
      - pnpm --filter backend dev & pnpm --filter frontend dev

  lint:
    desc: "Run ESLint and Prettier checks"
    cmds:
      - pnpm lint # Assumes pnpm is available and lint script is in root package.json

  typecheck:
    desc: "Run TypeScript compiler to check types"
    cmds:
      - echo "TODO: Implement typecheck task (tsc --noEmit)" # Placeholder

  test:
    desc: "Run Vitest unit tests"
    cmds:
      - pnpm test # Assumes pnpm is available and test script is in root package.json

  e2e:
    desc: "Run Playwright smoke tests"
    cmds:
      - echo "TODO: Implement e2e task (Playwright)" # Placeholder

  build:
    desc: "Run Vite build + tsc + docker build"
    cmds:
      - pnpm --filter frontend build
      - pnpm --filter backend build # Assuming backend also has a build script
      - docker build -t game-server . # Add appropriate tag

  default:
    cmds:
      - task: --list
