version: '3'

silent: true

tasks:
  install:
    desc: Install dependencies across all workspaces
    cmds:
      - pnpm install

  lint:
    desc: Run ESLint across all workspaces
    cmds:
      - pnpm exec eslint --ext .ts,.js,.tsx,.jsx apps/

  typecheck:
    desc: Run TypeScript type checking across all workspaces
    cmds:
      - pnpm --filter "./apps/**" exec tsc --noEmit

  test:
    desc: Run unit tests with Vitest
    cmds:
      - pnpm exec vitest run

  e2e:
    desc: Run end-to-end tests with Playwright
    cmds:
      - echo "E2E tests will be implemented in phase 1"
      # Will be implemented with: pnpm exec playwright test

  default:
    silent: true
    cmds:
      - task -l
