version: '3'

tasks:
  dev:
    desc: "Run Vite + Fastify in watch mode"
    cmds:
      - pnpm --filter frontend dev &
      - pnpm --filter backend dev

  lint:
    desc: "Run ESLint and Prettier checks"
    cmds:
      - pnpm lint

  typecheck:
    desc: "Run TypeScript compiler to check types"
    cmds:
      - pnpm -r typecheck

  test:
    desc: "Run Vitest unit tests"
    cmds:
      - pnpm test

  e2e:
    desc: "Run Playwright smoke tests"
    cmds:
      - echo "TODO - Implement e2e task"

  build:
    desc: "Run Vite build + tsc"
    cmds:
      - pnpm -r build

  default:
    cmds:
      - task --list
